Repository micronaut-projects/micronaut-grpc, pull requests merged in 2022-05, with the labels that each got.

#512 [grpc] Update common files for branch master
  .github/dependabot.yml
Labels: relates-to: build

#517 ci: action-junit-report@v3.0.3 and no dependencyUpdates
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#519 build: update grpc and protobuf
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#520 ci: GitHub actions sync files
  .github/release.yml
  .github/renovate.json
  .github/workflows/dependency-update.yml
Labels: relates-to: build

#516 Expose a gRPC Health Check for grpc-server
  gradle/libs.versions.toml
  grpc-server-runtime/build.gradle
  grpc-server-runtime/src/main/java/io/micronaut/grpc/server/GrpcServerBuilder.java
  grpc-server-runtime/src/main/java/io/micronaut/grpc/server/health/GrpcHealthFactory.java
  grpc-server-runtime/src/main/java/io/micronaut/grpc/server/health/HealthStatusManagerContainer.java
  grpc-server-runtime/src/test/groovy/io/micronaut/grpc/server/GrpcServerBuilderSpec.groovy
  grpc-server-runtime/src/test/groovy/io/micronaut/grpc/server/health/GrpcServerHealthSpec.groovy
  grpc-server-runtime/src/test/resources/logback.xml
  src/main/docs/guide/server.adoc
  test-suite-groovy/build.gradle
  test-suite-groovy/src/main/groovy/helloworld/HealthService.groovy
  test-suite-groovy/src/test/groovy/helloworld/HealthCheckSpec.groovy
  test-suite-java/build.gradle
  test-suite-java/src/main/java/helloworld/HealthService.java
  test-suite-java/src/test/java/helloworld/HealthCheckTest.java
  test-suite-kotlin/build.gradle
  test-suite-kotlin/src/main/kotlin/helloworld/HealthService.kt
  test-suite-kotlin/src/test/kotlin/helloworld/HealthCheckTest.kt
Labels: type: enhancement

#483 Upgrade libs. Fix versions for test suites
  .gitattributes
  gradle.properties
  test-suite-groovy/build.gradle
  test-suite-groovy/gradle/wrapper/gradle-wrapper.jar
  test-suite-java/.mvn/wrapper/maven-wrapper.properties
  test-suite-java/gradle.properties
  test-suite-java/gradle/wrapper/gradle-wrapper.jar
  test-suite-java/pom.xml
  test-suite-kotlin/build.gradle
  test-suite-kotlin/gradle/wrapper/gradle-wrapper.jar
  test-suite-kotlin/src/main/resources/META-INF/native-image/io.micronaut.grpc/test-suite-kotlin/native-image.properties
Labels: relates-to: build

#524 Memory Leak in ByteBufToProtoMessageConverter
  protobuff-support/src/main/java/io/micronaut/protobuf/convert/ByteBufToProtoMessageConverter.java
Labels: type: bug
